line-length = 100
target-version = "py311"

exclude = [
    ".venv",
    "build",
    "dist",
]

[lint]
# Expand rule set: E (pycodestyle errors), F (pyflakes), I (imports), UP (pyupgrade), SIM (simplify)
select = ["E", "F", "I", "UP", "SIM"]
ignore = []

[lint.isort]
known-first-party = ["app", "tests"]
combine-as-imports = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
