name: CI
on:
  push:
  pull_request:
jobs:
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix["python-version"] }}
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: python -m ruff check
      - name: Test
        run: python -m pytest -q --cov=app --cov-report=term-missing

